import {
  pgTable,
  varchar,
  text,
  timestamp,
  doublePrecision,
  boolean,
  integer,
  date,
  index,
} from "drizzle-orm/pg-core";

export const satelliteMetadata = pgTable(
  "satellite_metadata",
  {
    noradId: varchar("norad_id", { length: 10 }).primaryKey(),
    name: varchar("name", { length: 200 }),
    objectId: varchar("object_id", { length: 20 }),
    altName: varchar("alt_name", { length: 200 }),
    objectType: varchar("object_type", { length: 50 }),
    status: varchar("status", { length: 10 }),
    countryCode: varchar("country_code", { length: 50 }),
    launchDate: date("launch_date", { mode: "date" }),
    stableDate: date("stable_date", { mode: "date" }),
    launchSite: varchar("launch_site", { length: 100 }),
    launchPad: varchar("launch_pad", { length: 50 }),
    launchVehicle: varchar("launch_vehicle", { length: 100 }),
    flightNo: varchar("flight_no", { length: 50 }),
    cosparLaunchNo: varchar("cospar_launch_no", { length: 20 }),
    launchFailure: boolean("launch_failure"),
    launchSiteName: varchar("launch_site_name", { length: 100 }),
    decayDate: date("decay_date", { mode: "date" }),
    period: doublePrecision("period"),
    inclination: doublePrecision("inclination"),
    apogee: doublePrecision("apogee"),
    perigee: doublePrecision("perigee"),
    eccentricity: doublePrecision("eccentricity"),
    raan: doublePrecision("raan"),
    argOfPerigee: doublePrecision("arg_of_perigee"),
    rcs: varchar("rcs", { length: 20 }),
    stdMag: doublePrecision("std_mag"),
    tleEpoch: timestamp("tle_epoch", { mode: "date" }),
    tleAge: integer("tle_age"),
    cosparId: varchar("cospar_id", { length: 20 }),
    objectClass: varchar("object_class", { length: 50 }),
    launchMass: doublePrecision("launch_mass"),
    shape: text("shape"),
    dimensions: varchar("dimensions", { length: 50 }),
    span: doublePrecision("span"),
    mission: text("mission"),
    firstEpoch: date("first_epoch", { mode: "date" }),
    operator: varchar("operator", { length: 100 }),
    manufacturer: varchar("manufacturer", { length: 100 }),
    contractor: varchar("contractor", { length: 100 }),
    bus: varchar("bus", { length: 100 }),
    configuration: varchar("configuration", { length: 100 }),
    purpose: text("purpose"),
    power: text("power"),
    motor: text("motor"),
    length: doublePrecision("length"),
    diameter: doublePrecision("diameter"),
    dryMass: doublePrecision("dry_mass"),
    equipment: text("equipment"),
    adcs: text("adcs"),
    payload: text("payload"),
    constellationName: text("constellation_name"),
    lifetime: text("lifetime"),
    platform: varchar("platform", { length: 100 }),
    color: text("color"),
    materialComposition: text("material_composition"),
    majorEvents: text("major_events"),
    relatedSatellites: text("related_satellites"),
    transmitterFrequencies: text("transmitter_frequencies"),
    sources: text("sources"),
    referenceUrls: text("reference_urls"),
    summary: text("summary"),
    anomalyFlags: varchar("anomaly_flags", { length: 50 }),
    lastReviewed: timestamp("last_reviewed", { mode: "date" }),
    predDecayDate: date("pred_decay_date", { mode: "date" }),
    hasDiscosData: boolean("has_discos_data").default(false).notNull(),
    hasKeepTrackData: boolean("has_keeptrack_data").default(false).notNull(),
    hasSpaceTrackData: boolean("has_spacetrack_data").default(false).notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("satellite_metadata_country_code_idx").on(table.countryCode),
    index("satellite_metadata_object_type_idx").on(table.objectType),
    index("satellite_metadata_launch_date_idx").on(table.launchDate),
  ],
);
