import { pgTable, varchar, text, timestamp, doublePrecision, boolean, integer, date, index } from 'drizzle-orm/pg-core';

export const satelliteMetadata = pgTable(
  'satellite_metadata',
  {
    norad_id: varchar('norad_id', { length: 10 }).primaryKey(),
    name: varchar('name', { length: 200 }),
    object_id: varchar('object_id', { length: 20 }),
    alt_name: varchar('alt_name', { length: 100 }),
    alt_names: text('alt_names'),
    object_type: varchar('object_type', { length: 50 }),
    status: varchar('status', { length: 10 }),
    country_code: varchar('country_code', { length: 50 }),
    launch_date: date('launch_date', { mode: 'date' }),
    stable_date: date('stable_date', { mode: 'date' }),
    launch_site: varchar('launch_site', { length: 100 }),
    launch_pad: varchar('launch_pad', { length: 50 }),
    launch_vehicle: varchar('launch_vehicle', { length: 100 }),
    flight_no: varchar('flight_no', { length: 50 }),
    cospar_launch_no: varchar('cospar_launch_no', { length: 20 }),
    launch_failure: boolean('launch_failure'),
    launch_site_name: varchar('launch_site_name', { length: 100 }),
    decay_date: date('decay_date', { mode: 'date' }),
    period: doublePrecision('period'),
    inclination: doublePrecision('inclination'),
    apogee: doublePrecision('apogee'),
    perigee: doublePrecision('perigee'),
    eccentricity: doublePrecision('eccentricity'),
    raan: doublePrecision('raan'),
    arg_of_perigee: doublePrecision('arg_of_perigee'),
    rcs: varchar('rcs', { length: 20 }),
    std_mag: doublePrecision('std_mag'),
    tle_epoch: timestamp('tle_epoch', { mode: 'date' }),
    tle_age: integer('tle_age'),
    cospar_id: varchar('cospar_id', { length: 20 }),
    object_class: varchar('object_class', { length: 50 }),
    launch_mass: doublePrecision('launch_mass'),
    shape: varchar('shape', { length: 100 }),
    dimensions: varchar('dimensions', { length: 50 }),
    span: doublePrecision('span'),
    mission: varchar('mission', { length: 100 }),
    first_epoch: date('first_epoch', { mode: 'date' }),
    operator: varchar('operator', { length: 100 }),
    manufacturer: varchar('manufacturer', { length: 100 }),
    contractor: varchar('contractor', { length: 100 }),
    bus: varchar('bus', { length: 100 }),
    configuration: varchar('configuration', { length: 100 }),
    purpose: text('purpose'),
    power: text('power'),
    motor: text('motor'),
    length: doublePrecision('length'),
    diameter: doublePrecision('diameter'),
    dry_mass: doublePrecision('dry_mass'),
    equipment: text('equipment'),
    adcs: text('adcs'),
    payload: text('payload'),
    constellation_name: varchar('constellation_name', { length: 100 }),
    lifetime: varchar('lifetime', { length: 100 }),
    platform: varchar('platform', { length: 100 }),
    color: varchar('color', { length: 100 }),
    material_composition: text('material_composition'),
    major_events: text('major_events'),
    related_satellites: text('related_satellites'),
    transmitter_frequencies: text('transmitter_frequencies'),
    sources: text('sources'),
    reference_urls: text('reference_urls'),
    summary: text('summary'),
    anomaly_flags: varchar('anomaly_flags', { length: 50 }),
    last_reviewed: timestamp('last_reviewed', { mode: 'date' }),
    pred_decay_date: date('pred_decay_date', { mode: 'date' }),
    has_discos_data: boolean('has_discos_data').default(false).notNull(),
    has_keeptrack_data: boolean('has_keeptrack_data').default(false).notNull(),
    has_spacetrack_data: boolean('has_spacetrack_data').default(false).notNull(),
    created_at: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
    updated_at: timestamp('updated_at', { mode: 'date' }).defaultNow().notNull(),
  },
  (table) => [
    index('satellite_metadata_country_code_idx').on(table.country_code),
    index('satellite_metadata_object_type_idx').on(table.object_type),
    index('satellite_metadata_launch_date_idx').on(table.launch_date),
  ]
);